apiVersion: v1
kind: Service
metadata:
  #annotations:
    #argocd.argoproj.io/sync-options: Delete=false
  name: guestbook-ui-delete-false
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
