apiVersion: v1
kind: Service
metadata:
  annotations:
    # No Prune at resource level
    argocd.argoproj.io/sync-options: Prune=false,Validate=false
  name: guestbook-ui-syncoptions-multiple
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
